### ISSUE TITLE
A code mistake in the exercise "Soup or no soup" part 1 conditional statements. Doesn't accept the right answers.

### ISSUE THREAD

**Issue by PavelLange** [rage/programming-24#5]
I wrote a code (below) and I checked it many times through Visual Studio and it works perfectly well but when I press the button submit it shows an error that reads: 

_FAIL: PythonEditorTest: test_1_kramer_1
With input Kramer, 1 your program should print out
Next please!
your program printed out
The total cost is 5.9_

So I fixed as asked and it gives the same response that reads: 

_FAIL: PythonEditorTest: test_1_kramer_1
With input Kramer, 1 your program should print out
The total cost is 5.9
your program printed out
Next please!_

I even tried to replace in my code the line number 5 with "else:" and the error is still the same. Is there anything wrong with the exercise or my code should look somehow different? 

The code:

name = input("Please tell me your name: ")
price = 5.90
if name == "Jerry":
    print("Next please!")
if name != "Jerry":
    portions = int(input("How many portions of soup? "))
    total = portions * price
    print(f"The total cost is {total}")

**Comment by aygupt1822** [comment]
Probably the indentation in if block can be the issue...
`name = input("Please tell me your name: ")
price = 5.90
if name == "Jerry":
    print("Next please!")
if name != "Jerry":
    portions = int(input("How many portions of soup? "))
total = portions * price
print(f"The total cost is {total}")`
